### ISSUE TITLE
Clamping in Affine Transform

### ISSUE THREAD

**Issue by vpratz** [bayesflow-org/bayesflow#253]
The changes in clamping have lead to worse performance in the two moons test. Reverting the changes in eb5c446b0268ef596 and 7906c1e23eee5882888cfff9456b83ca4670026d fixed this, but was not motivated by extensive testing.

@stefanradev93 Could you please evaluate which form is the best in practice and, in case the changes are the best in practical applications, adjust the test settings accordingly?

**Comment by stefanradev93** [comment]
That was also my experience, so I picked the settings that stabilized training on the regression and two moons examples (basically the old settings from 1.5x).

However, using my "stable" settings, @elseml got NaNs in his experiments. It seems that stability is currently a bit dependent on the test case, which needs to be solved.

My last suspicion is in the residual net, which we preciously didn't use.

**Comment by vpratz** [comment]
Thanks for the additional information. I just reran `pytest tests/test_two_moons` a few times on https://github.com/bayesflow-org/bayesflow/commit/eb5c446b0268ef5960f06eb475a549dd9486a82b and now it passes for me locally. When I [ran it earlier](https://github.com/bayesflow-org/bayesflow/actions/runs/11950487461/job/33312070491) it failed, producing a value that was too high.

The problem with the NaNs seems to persist, see #254.

What would be your preferred configuration until we have figured this out? Using the code from https://github.com/bayesflow-org/bayesflow/commit/eb5c446b0268ef5960f06eb475a549dd9486a82b?

**Comment by stefanradev93** [comment]
I am on it.

**Comment by stefanradev93** [comment]
I have a setting that produced no NaNs in loss or samples over three runs across:

- Two moons
- SIR
- Regression

I will push my commit, and @elseml and @vpratz  can decide whether to keep it or not upon further testing.

**Comment by stefanradev93** [comment]
Let me know if you still observe some problems after my recent push.

**Comment by elseml** [comment]
Quick timeline of my experiences (note that my setup is more prone to NaNs in general):
- Commit aeee627 introduces major instabilities (~ NaN in 60% of runs)
- Reverting its changes to `affine_transform.py` in commit eb5c446 fixed the issue
- The changes to `affine_transform.py` in commit 7906c1e led to NaNs in ~10% of runs (quite hard to test due to their rare occurence) and an extremly high loss at the beginning of the training (larger by factor ~4000 compared to before) but not later on
- I encountered no NaNs after commit 3878625 yet (cannot be ruled out due to their rare occurence, I will update when it changes) and it fixed the exploding loss at the beginning of the training

The issue can thus be closed for now from my side - we will have to see in the long run if the occasional instabilities in #254 were sufficiently addressed.

**Comment by vpratz** [comment]
Thanks, let's keep an eye on this an reopen the issue when needed.

**Comment by paul-buerkner** [comment]
Great! Thank you all for helping to fix this issue!
